### ISSUE TITLE
Opensource checklist

### ISSUE THREAD

**Issue by annejan** [minvws/nl-rdo-php-audit-logger-bundle#13]
- [x] Update documentation
- [x] Sanity check the code and commits
- [x] Check License
  - [ ]  [REUSE](https://reuse.software/uk/spec-3.2/)
- [ ] README check
  - [ ] Readability (use of domain terminology)
- [ ] Check if code is not used in other repositories
- [ ] Add known secrets to README or security information file
- [ ] Get written approval
  - [ ] Product owner
  - [ ] Management team (RDO specific: CTO)
- [ ] Configure repo for public archive
- [ ] Celebrate 🎉
